[workspace]
members = ["contracts/*"]

[profile.release.package.lido-terra-stluna-bluna-converter-contract]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true

